from pydantic import BaseModel, EmailStr
from typing import Optional
from typing import List

# Import the UserRole enum from your models to ensure consistency
from app.models.user import UserRole

# -- Base Schemas --
# Shared properties that are common to most schemas.
class UserBase(BaseModel):
    email: EmailStr
    full_name: Optional[str] = None
    role: UserRole

# -- Schemas for API Input --
# Properties to receive via API on creation.
class UserCreate(UserBase):
    password: str

# Properties to receive via API on update.
class UserUpdate(BaseModel):
    email: Optional[EmailStr] = None
    full_name: Optional[str] = None
    password: Optional[str] = None
    role: Optional[UserRole] = None
    is_active: Optional[bool] = None


# -- Schemas for API Output --
# Properties to return to the client.
# This is the main schema for reading a user's data.
# It inherits from UserBase and adds fields that are generated by the database.
class User(UserBase):
    id: int
    is_active: bool

    class Config:
        # This tells Pydantic to read the data even if it is not a dict,
        # but an ORM model (or any other arbitrary object with attributes).
        from_attributes = True
        
# --- Schema for Bulk Creation ---
class UserBulkCreate(BaseModel):
    users: List[UserCreate]